name: workspace_scripts
description: A helper for dart workspace projects
version: 0.0.1
repository: https://github.com/mintware-de/workspace_scripts

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  yaml: ^3.1.3
  path: ^1.9.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  lints: ^5.0.0
  test: ^1.24.0

executables:
  workspace_scripts: